[package]
name = "bhava"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4"
wasm-bindgen = "0.2"
wasm-bindgen-test = "0.3"
wasm-logger = "0.2"
web-sys = { version = "0.3", features = ["DomTokenList", "HtmlDivElement", "NodeList"] }
yew = "0.19"
